"""
CONCEPT: Prompt chaining — decomposing one complex task into a SEQUENCE of
smaller, focused LLM calls, where each call's output becomes the next
call's input.

Why chain instead of one big prompt?
  - Each step has ONE narrow job (outline, draft, edit) instead of trying
    to do everything in a single instruction. Models are more reliable at
    a small, well-scoped task than at a large, multi-part one.
  - Intermediate results are inspectable — you can see (and log) exactly
    what the outline looked like before the draft was written from it.
  - You can insert a programmatic "gate" between steps: plain Python code
    that checks a step's output and can stop the chain early if something
    looks wrong, before spending tokens on the next (possibly expensive)
    step.

This is different from ../../Tools_and_Actions/tool_use/basic_agentic_tools.py's agentic loop, where the
MODEL decides what happens next (which tool to call, when to stop) and the
number of steps isn't known in advance. In prompt chaining, YOUR CODE
decides the sequence of steps ahead of time — the control flow is fixed;
only the CONTENT flowing through each step is generated by the model. In
Anthropic's terminology this makes it a "workflow", not an autonomous
agent.

It's also different from ../../Execution_Loops/agentic_loop/basic_agentic_loop.py's chat: each step below
gets its OWN focused system prompt and a small, specific input — not a
shared, ever-growing conversation history. Keeping each call's context
narrow and single-purpose is part of what makes chaining reliable.

Use case: generate a short blog post from a topic, via three chained
steps — outline, draft, edit — with a validation gate right after the
outline step.

Type 'exit' at the topic prompt to quit.
"""

from __future__ import annotations

import os
import sys

import anthropic

# --- API settings (see ../../basics/basic.py for what each of these means) ---
MODEL = "claude-sonnet-5"
MAX_TOKENS = 4096
EFFORT = "medium"

client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from the environment


def call_step(system_prompt: str, user_content: str) -> str:
    """Run one link in the chain: a single, stateless LLM call scoped to
    just this step's job via its own system prompt. Each step has no
    memory of any other step except whatever text we explicitly pass in as
    `user_content` — unlike the chat templates, there is no shared
    `messages` history accumulating across the whole chain.
    """
    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=system_prompt,
        output_config={"effort": EFFORT},
        messages=[{"role": "user", "content": user_content}],
    )
    return "".join(block.text for block in response.content if block.type == "text")


# ---------------------------------------------------------------------------
# STEP 1: Outline
# ---------------------------------------------------------------------------
# A narrow, single-purpose prompt: this step's ONLY job is producing an
# outline. It doesn't know or care about drafting or editing.
OUTLINE_SYSTEM_PROMPT = (
    "You write blog post outlines. Given a topic, respond with ONLY a "
    "bulleted list of 3-6 section headers for the post — no intro, no "
    "explanation, no draft content. One header per line, each starting "
    "with '- '."
)


def generate_outline(topic: str) -> str:
    return call_step(OUTLINE_SYSTEM_PROMPT, f"Topic: {topic}")


# ---------------------------------------------------------------------------
# GATE: a programmatic (non-LLM) check between steps.
# ---------------------------------------------------------------------------
# CONCEPT: gates are plain code, not model calls — cheap, fast, and fully
# deterministic. They let the chain fail fast: if the outline is too thin
# to build a real post from, there's no point spending tokens on a draft
# step that's doomed to be shallow too. A gate can also branch the chain
# (e.g. re-run a step with feedback) instead of just stopping — this
# template keeps it simple and stops.
def validate_outline(outline: str) -> tuple[bool, str]:
    sections = [line for line in outline.splitlines() if line.strip().startswith("-")]
    if len(sections) < 3:
        return False, f"Outline only has {len(sections)} section(s); need at least 3."
    return True, f"Outline has {len(sections)} sections — looks good."


# ---------------------------------------------------------------------------
# STEP 2: Draft
# ---------------------------------------------------------------------------
DRAFT_SYSTEM_PROMPT = (
    "You write blog post drafts. Given a topic and an outline, write a full "
    "draft following that outline exactly — one section per outline "
    "header, in order. Keep each section to 2-3 short paragraphs."
)


def write_draft(topic: str, outline: str) -> str:
    # CONCEPT: chaining in action — this step's input is literally built
    # from the PREVIOUS step's output. The outline text generated above
    # flows directly into this prompt.
    return call_step(DRAFT_SYSTEM_PROMPT, f"Topic: {topic}\n\nOutline:\n{outline}")


# ---------------------------------------------------------------------------
# STEP 3: Edit
# ---------------------------------------------------------------------------
EDIT_SYSTEM_PROMPT = (
    "You are a copy editor. Tighten the following draft: fix grammar, cut "
    "redundant phrasing, and improve flow between paragraphs. Preserve the "
    "section headers and the overall structure and meaning. Return only "
    "the edited post."
)


def edit_draft(draft: str) -> str:
    # Same idea again — this step only ever sees the draft, not the
    # original topic or the outline. It doesn't need them for its job.
    return call_step(EDIT_SYSTEM_PROMPT, draft)


# ---------------------------------------------------------------------------
# The chain itself: a fixed sequence of steps, decided by code, not the
# model. This is the defining trait of prompt chaining — compare this
# straight-line function to run_turn() in ../../Tools_and_Actions/tool_use/basic_agentic_tools.py, where
# the number and order of steps is NOT known ahead of time because the
# model decides it dynamically.
# ---------------------------------------------------------------------------
def run_chain(topic: str) -> str | None:
    print("\n[1/3] Generating outline...")
    outline = generate_outline(topic)
    print(outline)

    passed, reason = validate_outline(outline)
    print(f"[gate] {reason}")
    if not passed:
        print("[gate] Outline failed validation — stopping the chain before drafting.")
        return None

    print("\n[2/3] Writing draft from outline...")
    draft = write_draft(topic, outline)
    print(draft)

    print("\n[3/3] Editing draft...")
    edited = edit_draft(draft)

    return edited


def main() -> None:
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print(
            "Set ANTHROPIC_API_KEY in your environment before running this script.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("Blog post generator (prompt chaining demo). Type 'exit' to quit.\n")

    while True:
        topic = input("Topic: ").strip()
        if topic.lower() == "exit":
            print("Goodbye!")
            break
        if not topic:
            continue

        result = run_chain(topic)
        if result is not None:
            print("\n=== Final post ===\n")
            print(result)
            print()


if __name__ == "__main__":
    main()
