"""
CONCEPT: Plan-and-Execute — a two-phase pattern. First, generate a high-
level PLAN: break a complex task into a sequence of concrete steps.
Second, EXECUTE each step in order, one at a time, using the results of
completed steps as context for the ones that follow.

Compare this with ../../prompt_chaining/basic_prompt_chaining.py: that
template also runs a fixed sequence of steps (outline -> draft -> edit),
but the sequence itself is HARDCODED by the developer ahead of time —
always exactly those three steps, for every input. Plan-and-Execute is
more general: the PLAN ITSELF is generated by the model, tailored to
whatever task comes in, so a simple task might get 3 steps and a complex
one might get 7 — the developer only writes the planning and execution
MACHINERY, not the specific steps.

Each step is executed by a focused call given the overall task, the full
plan for context, and every prior step's result — a "sub-agent" scoped
to just that one step. Real Plan-and-Execute systems often give each
step's sub-agent its OWN tools (a research step might get a search tool,
a coding step might get a code-execution tool); this template keeps
execute_step tool-free to isolate the plan/execute mechanic on its own,
but the extension is straightforward — give execute_step a `tools=`
parameter and a loop, the same way ../../tool_use/basic_agentic_tools.py
does.

The plan is produced as structured output (`output_config.format`,
covered in ../../tool_use/README.md) rather than parsed out of free-text
numbering — a clean, reliable list of steps instead of regex-ing a
numbered list.

Type 'exit' to quit.
"""

from __future__ import annotations

import json
import os
import sys

import anthropic

# --- API settings (see ../../basics/basic.py for what each of these means) ---
MODEL = "claude-sonnet-5"
MAX_TOKENS = 2048
EFFORT = "medium"

client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from the environment

PLAN_SYSTEM_PROMPT = (
    "You are a planning assistant. Break the given task into a short "
    "sequence of 3 to 5 concrete, executable steps. Each step should be "
    "a single clear instruction that can be carried out on its own, "
    "given the results of the steps before it."
)

PLAN_SCHEMA = {
    "type": "object",
    "properties": {
        "steps": {
            "type": "array",
            "items": {"type": "string"},
            "description": "The ordered list of steps to execute",
        },
    },
    "required": ["steps"],
    "additionalProperties": False,
}


def generate_plan(task: str) -> list[str]:
    """CONCEPT: the PLAN phase. One call, producing a structured list of
    steps — this is the only place in the whole pipeline where the
    overall shape of the work gets decided.
    """
    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=PLAN_SYSTEM_PROMPT,
        output_config={"effort": EFFORT, "format": {"type": "json_schema", "schema": PLAN_SCHEMA}},
        messages=[{"role": "user", "content": task}],
    )
    text = "".join(block.text for block in response.content if block.type == "text")
    return json.loads(text)["steps"]


def execute_step(task: str, plan: list[str], step_index: int, prior_results: list[str]) -> str:
    """CONCEPT: the EXECUTE phase, one step at a time. This function acts
    as a mini sub-agent: it's handed the overall goal, the full plan for
    context, and everything completed so far, but its job is narrowly
    scoped to producing THIS step's result — not the whole task.
    """
    plan_display = "\n".join(f"{i + 1}. {step}" for i, step in enumerate(plan))
    completed_display = "\n\n".join(
        f"Step {i + 1} ({plan[i]}):\n{result}" for i, result in enumerate(prior_results)
    ) or "(none yet)"

    prompt = (
        f"Overall task: {task}\n\n"
        f"Full plan:\n{plan_display}\n\n"
        f"Completed steps so far:\n{completed_display}\n\n"
        f"Now execute step {step_index + 1}: {plan[step_index]}\n"
        "Focus only on this step — don't redo earlier steps or jump ahead."
    )
    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system="You are executing one step of a larger plan. Produce only this step's result.",
        output_config={"effort": EFFORT},
        messages=[{"role": "user", "content": prompt}],
    )
    return "".join(block.text for block in response.content if block.type == "text")


def plan_and_execute(task: str) -> str:
    plan = generate_plan(task)
    print("\nPlan:")
    for i, step in enumerate(plan):
        print(f"  {i + 1}. {step}")

    results: list[str] = []
    for i in range(len(plan)):
        print(f"\n[{i + 1}/{len(plan)}] Executing: {plan[i]}")
        result = execute_step(task, plan, i, results)
        print(result)
        results.append(result)

    # The last step's result serves as the final answer — the plan is
    # expected to end with a synthesis/conclusion step. A stricter
    # version could add an explicit final synthesis call instead of
    # relying on the plan's last step to do that job.
    return results[-1]


def main() -> None:
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print(
            "Set ANTHROPIC_API_KEY in your environment before running this script.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("Plan-and-Execute demo. Type 'exit' to quit.\n")
    print(
        "Try: \"Compare the pros and cons of remote work vs. office work "
        "and recommend a policy.\"\n"
    )

    while True:
        task = input("Task: ").strip()
        if task.lower() == "exit":
            print("Goodbye!")
            break
        if not task:
            continue

        final_result = plan_and_execute(task)
        print(f"\n=== Final result ===\n{final_result}\n")


if __name__ == "__main__":
    main()
